# Generated by Django 3.1.6 on 2023-01-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="І'мя Фамілія")),
                ('img', models.ImageField(upload_to='Models-Cover/Profile-Img/', verbose_name='Фото обкладинки')),
                ('profile_img', models.FileField(blank=True, null=True, upload_to='', verbose_name='Інші фото')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('score', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Кількість балів')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Моделі',
            },
        ),
    ]
