# Generated by Django 3.1.6 on 2023-01-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва пакету')),
                ('price', models.IntegerField(default=0, verbose_name='Ціна')),
                ('vote', models.IntegerField(default=0, verbose_name='Кількість голосів')),
            ],
        ),
    ]
